function void InitMOP(void)
{
	AddWeapon("NewFist");
	AddWeapon("NewPistol");
	AddWeapon("NewChainsaw");
	AddWeapon("NewShotgun");
	AddWeapon("NewSuperShotgun");
	AddWeapon("NewChaingun");
	AddWeapon("NewRocketLauncher");
	AddWeapon("NewPlasmaRifle");
	AddWeapon("NewBFG9000");
	AddWeapon("ShieldGenerator");
	
	AddStartItem("NewPistol", 1);
	AddStartItem("Clip", 50);
	AddStartItem("NewFist", 1);
	AddStartItem("PistolClip", 12);
	AddStartItem("ShotgunClip", 8);
	AddStartItem("ChaingunClip", 40);
	AddStartItem("SSGClip", 2);
	AddStartItem("PlasmaClip", 50);
	AddStartItem("RocketClip", 5);
	
	AddMonster(0.02,  "POSSA1",   "Zombieman2", "Zombieman");
	
	AddMonster(0.04,  "SPOSA1",   "Shotgunguy2", "Shotgun Zombie");
	AddMonster(0.07,  "ESPSA1",   "EliteShotgunGuy", "Elite Shotgun Zombie");
	
	AddMonster(0.05,  "CPOSA1",   "Chaingunguy2", "Zombie Commando");
	
	AddMonster(0.02,  "TROOA1",   "Imp2", "Imp");
	AddMonster(0.05,  "DRKVA1",   "DarkImp", "Dark Imp");
	
	AddMonster(0.045, "SARGA1",   "Pinky", "Demon");
	//AddMonster(0.075, "BDMNA1",   "Fiend", "Fiend");
	AddMonster(0.0475,"SPTRA1",   "Spectre2", "Spectre");
	//AddMonster(0.08,  "SBDMA1",   "Shadow Fiend", "ShadowFiend");
	
	AddMonster(0.07,  "SKULA1",   "LostSoul2", "Lost Soul"); FlyingMonster();
	
	AddMonster(0.15,  "HEADA1",   "Cacodemon2", "Cacodemon"); FlyingMonster();
	//AddMonster(0.2,   "LANTA1",   "Cacolantern", "Cacolantern"); FlyingMonster();
	//AddMonster(0.3,   "ABDNA1",   "Abaddon", "Abaddon"); FlyingMonster();
	
	AddMonster(0.2,   "PAINA1",   "PainElemental2", "Pain Elemental"); FlyingMonster();
	AddMonster(0.15,  "BOS2A1C1", "HellKnight2", "Hell Knight");
	
	AddMonster(0.25,  "BOSSA1",   "BaronofHell2", "Baron of Hell");
	//AddMonster(0.325,  "BELPA1",   "Belphegor", "Belphegor");
	
	AddMonster(0.15,  "SKELA1D1", "Revenant2", "Revenant");
	
	AddMonster(0.2,   "FATTA1",   "Mancubus", "Mancubus");
	//AddMonster(0.3,   "FAT2A1",   "Hectebus", "Hectebus");
	
	AddMonster(0.2,   "BSPIA1D1", "Arachnotron2", "Arachnotron");
	AddMonster(0.5,   "VILEA1D1", "Archvile2", "Arch-Vile");
	AddMonster(5.0,   "SPIDA1D1", "Spidermastermind2", "Spider Mastermind"); BossMonster();
	AddMonster(6.0,   "CYBRA1",   "Cyberdemon2", "Cyberdemon"); BossMonster();
	AddMonster(0.02,  "SSWVA1",   "WolfensteinSS2", "Wolfenstein SS");
	
	AddMonster(0.01,  "BAR1A0",   "NewExplosiveBarrel", "Explosive Barrel");
}
