function void InitMOP(void)
{
	AddWeapon("NewFist");
	AddWeapon("NewPistol");
	AddWeapon("NewChainsaw");
	AddWeapon("NewShotgun");
	AddWeapon("NewSuperShotgun");
	AddWeapon("NewChaingun");
	AddWeapon("NewRocketLauncher");
	AddWeapon("NewPlasmaRifle");
	AddWeapon("NewBFG9000");
	AddWeapon("ShieldGenerator");
	
	AddStartItem("NewPistol", 1);
	AddStartItem("Clip", 50);
	AddStartItem("NewFist", 1);
	AddStartItem("ShotgunClip", 8);
	AddStartItem("ChaingunClip", 40);
	AddStartItem("SSGClip", 2);
	AddStartItem("PlasmaClip", 50);
	AddStartItem("RocketClip", 5);
	
	addmonster(0.02, "POSSA1", "ROPzombieman", "\cbZombieman");
	
	addmonster(0.035, "SPOSA1", "ROPshotgunguy", "\cuShotgun Zombie");
	
	addmonster(0.05, "CPOSA1", "ROPchaingunguy", "\caChaingun Zombie");
	
	addmonster(0.03, "TROOA1", "ROPimp", "\ceImp");
	
	addmonster(0.045, "SARGA1", "ROPpinky", "\caPinky");
	
	addmonster(0.05, "SPTRA1", "ROPspectre", "\cuSpectre");
	
	addmonster(0.06, "SKULA1", "ROPlostsoul", "\ciLost Soul"); FlyingMonster();
	
	addmonster(0.125, "HEADA1", "cacodemon", "\cgCacodemon"); FlyingMonster();
	
	addmonster(0.14, "BOS2A1C1", "hellknight", "\cbHell Knight");
	
	addmonster(0.15, "SKELA1D1", "revenant", "\ccRevenant");
	
	addmonster(0.175, "PAINA1", "painelemental", "\cePain Elemental"); FlyingMonster();
	
	addmonster(0.175, "BSPIA1D1", "arachnotron", "\cbArachnotron");
	
	addmonster(0.2, "FATTA1", "fatso", "\ceMancubus");
	
	addmonster(0.225, "BOSSA1", "baronofhell", "\caBaron of Hell");
	
	addmonster(0.3, "VILEA1D1", "archvile", "\coArch-Vile");
	
	addmonster(5.0, "SPIDA1D1", "spidermastermind", "\c[j4]Spider Mastermind"); BossMonster();
	
	addmonster(6.0, "CYBRA1", "cyberdemon", "\c[g5]Cyberdemon"); BossMonster();
	
	addmonster(0.025, "SSWVA1", "wolfensteinss", "\chWolfenstein \ckSS");
	
	addmonster(0.01, "BAR1A0", "explosivebarrel", "\cdExplosive Barrel");
	/*
	AddMonster(0.02,  "POSSA1",   "Zombieman2", "Zombieman");
	AddMonster(0.035, "PRPSA1",   "PlasmaZombie", "Plasma Zombie");
	
	AddMonster(0.04,  "SPOSA1",   "Shotgunguy2", "Shotgun Zombie");
	AddMonster(0.07,  "FPOSA1",   "Supershotgunguy", "Super Shotgun Zombie");
	
	AddMonster(0.05,  "CPOSA1",   "Chaingunguy2", "Zombie Commando");
	AddMonster(0.075, "DPOSA1C1",   "DoubleChainGunGuy", "Double Chaingunner");
	
	AddMonster(0.02,  "TROOA1",   "Imp2", "Imp");
	AddMonster(0.045, "SLHVA1",   "SoulHarvester", "Soul Harvester");
	AddMonster(0.05,  "DRKVA1",   "DarkImp", "Dark Imp");
	
	AddMonster(0.045, "SARGA1",   "Pinky", "Demon");
	AddMonster(0.065, "MDMNA1C1", "MechDemon", "Mech Demon");
	AddMonster(0.0475,"SPTRA1",   "Spectre2", "Spectre");
    AddMonster(0.07,  "MSPCA1C1", "Mechtre", "Mechtre");
	
	AddMonster(0.07,  "SKULA1",   "LostSoul2", "Lost Soul"); FlyingMonster();
	
	AddMonster(0.15,  "HEADA1",   "Cacodemon2", "Cacodemon"); FlyingMonster();
	AddMonster(0.2,   "LANTA1",   "Cacolantern", "Cacolantern"); FlyingMonster();
	AddMonster(0.25,  "ABDNA1",   "Abaddon", "Abaddon"); FlyingMonster();
	
	AddMonster(0.2,   "PAINA1",   "PainElemental2", "Pain Elemental"); FlyingMonster();
	
	AddMonster(0.15,  "BOS2A1C1", "HellKnight2", "Hell Knight");
	
	AddMonster(0.25,  "BOSSA1",   "BaronofHell2", "Baron of Hell");
	AddMonster(0.325, "BELPA1",   "Belphegor", "Belphegor");
	
	AddMonster(0.15,  "SKELA1D1", "Revenant2", "Revenant");
	
	AddMonster(0.2,   "FATTA1",   "Mancubus", "Mancubus");
	AddMonster(0.275, "HECTA1",   "Hectebus", "Hectebus");
	
	AddMonster(0.2,   "BSPIA1D1", "Arachnotron2", "Arachnotron");
	AddMonster(0.25,   "CSPIA1D1", "ArachnoSentinel", "Arachno-Sentinel");
	
	AddMonster(0.4,   "VILEA1D1", "Archvile2", "Arch-Vile");
	
	AddMonster(5.0,   "SPIDA1D1", "Spidermastermind2", "Spider Mastermind"); BossMonster();
	
	AddMonster(6.0,   "CYBRA1",   "Cyberdemon2", "Cyberdemon"); BossMonster();
	
	AddMonster(0.02,  "SSWVA1",   "WolfensteinSS2", "Wolfenstein SS");
	
	AddMonster(0.01,  "BAR1A0",   "NewExplosiveBarrel", "Explosive Barrel");
	*/
}

function void PistolStartModes(int mode)
{
	if (mode == 1)
	{
		print(s:"Pistol Start");
	}
	else if (mode == 2)
	{
		print(s:"Shotgun Start");
		GiveInventory("NewShotgun", 1);
	}
	else
	{
		print(s:"Shieldgun (slot 8) and Shotgun Start");
		GiveInventory("ShieldGenerator", 1);
		GiveInventory("NewShotgun", 1);
	}
}
