#library "rop"
#include "zcommon.acs"
#import "mopengine.acs"

#include "rop_decorate.acs"
#include "rop_utils.acs"

#define max_monsterinfo 14

// Pistol start script.
script "rop_pistolstart" ENTER
{
	if (!IsMarine())
		terminate;

	int mode = GetCVar("rop_pistolstartmode");
	if (mode == 0)
	{
		print(s:"Pistol Start");
	}
	else if (mode == 1)
	{
		print(s:"Shotgun Start");
		GiveInventory("NewShotgun", 1);
	}
	else
	{
		print(s:"Shieldgun (slot 8) and Shotgun Start");
		GiveInventory("ShieldGenerator", 1);
		GiveInventory("NewShotgun", 1);
	}
}

str monsterinfo[max_monsterinfo] =
{
	"Primary fire will fire your rifle. \nSecondary fire will charge a perfectly accurate shot. \n(\cdperfectly accurate, deals slightly more damage,\cgtakes 1 second to charge\c-)",
	
	"Primary fire will fire your shotgun. \nSecondary fire will fire shrapnels. \n(\cdcan bounce off walls, \cgless damage, affected by gravity\c-)",
	
	"Primary fire will fire your chaingun. \n(gets less accurate the more you shoot, stop firing to regain accuracy) \nSecondary fire revs your chaingun up. \n(\cdfaster firing, \cgreduced movement speed, cannot regain accuracy while reved up\c-)",
	
	"Primary fire will throw a fireball. \nSecondary fire will use your melee attack. \n(\cdhigher dps, \cglimited range\c-)",
	
	"Primary fire will mini-lunge. \nSecondary fire will bite. \n(\cdhigher dps, \cgdoesn't thrust forward\c-)",
	
	"\cdSpectres are partially invisible. \n\nPrimary fire will perform a mini-lunge. \nSecondary fire will bite. \n(\cdhigher dps, \cgdoesn't thrust forward\c-)",
	
	"\cdLost souls can fly. \n\cdLost souls gain 7 mana every second (\cgwhile not attacking\cd). \n\nPrimary fire will charge. \nSecondary fire will cause splash damage until mana runs out. \n(\cgRequires 15 mana to initiate\c-)",
	
	"\cdCacodemons can fly. \n\cdCacodemons can dodge. (double tap strafe keys) \n\nPrimary fire will fire electric projectiles. \nSecondary fire will bite. \n(\cdhigher dps, \cglimited range\c-)",
	
	"\cgHell knights have reduced jump height. \n\nPrimary fire will throw plasma. \nSecondary fire will punch. \n(\cdhigher dps, \cglimited range\c-)",
	
	"\cgRevenants have reduced jump height. \n\nPrimary fire will fire a rocket from your left cannon. \nSecondary fire will fire a rocket from your right cannon. \nReloading will toggle homing rockets. \n(\cgWill only home in if you are targeting something, Slightly reduced damage and speed\c-) \nZooming will punch. \n(\cdhigher dps, \cglimited range\c-)",
	
	"\cdPain elementals can fly. \n\cdPain elementals gain mana over time. \n\nPrimary fire will fire a suicidal lost soul. \nSecondary fire will bite \n(\cdhigher dps, \cglimited range\c-) \nReloading will spawn a lost soul when you have 100 mana. \n(\cgLimited to 10 lostsouls\c-)",
	
	"", //arachnotron
	
	"", //mancubus
	
	"\cgBarons have reduced jump height. \n\cdBarons gain mana after a while of not attacking. \n\nPrimary fire will throw plasma. \n(the more mana you have, the faster the projectile will be. projectiles use 2 mana, you can throw plasma without any mana.\c-) \nSecondary fire will punch. \n(\cdhigher dps, \cglimited range\c-)"
};

script "rop_possess" (int monster)
{
    if(getcvar("rop_possessmessage"))
	{
		print(s: "-", s:MonsterName(monster), s: "\c--\n\n", s:monsterinfo[monster]); 
	}
	
	if (MonsterActorName(monster) == "ROPpainelemental")
		ACS_NamedExecuteWithResult("rop_manaregen");
}

#define MANAREGEN_RATE 10.0 // per second

script "rop_manaregen" (void)
{
	int accum = 0.0;
	while (IsPossessed())
	{
		accum += MANAREGEN_RATE / 35;
		GiveInventory("painelementalmana", itrunc(accum));
		accum = fract(accum);
		Delay(1);
	}
}

// MOP init script called by MOP Engine.
script 800 (void)
{
	MOPOnPossess("rop_possess");

	addmonster(0.02, "POSSA1", "ROPzombieman", "\c[arachno]Zombieman");
	
	addmonster(0.035, "SPOSA1", "ROPshotgunguy", "\c[sergeant]Shotgun Zombie");
	
	addmonster(0.05, "CPOSA1", "ROPchaingunguy", "\c[chainguy]Chaingun Zombie");
	addmonsteritem("chaingunspintoken");
	
	addmonster(0.03, "TROOA1", "ROPimp", "\c[imp]Imp");
	
	addmonster(0.045, "SARGA1", "ROPpinky", "\c[pinky]Pinky");
	
	addmonster(0.05, "SPTRA1", "ROPspectre", "\c[sergeant]Spectre");
	
	addmonster(0.06, "SKULA1", "ROPlostsoul", "\ciLost Soul"); FlyingMonster();
	
	addmonster(0.125, "HEADA1", "ROPcacodemon", "\c[caco]Cacodemon"); FlyingMonster(); EvadingMonster(20);
	
	addmonster(0.15, "BOS2A1C1", "ROPhellknight", "\c[knight]Hell Knight");
	
	addmonster(0.15, "SKELA1D1", "ROPrevenant", "\cjRevenant");
	
	addmonster(0.175, "PAINA1", "ROPpainelemental", "\c[pain]Pain Elemental"); FlyingMonster();
	addmonsteritem("painsoullimit");
	addmonsteritem("painelementalmana");
	
	addmonster(0.175, "BSPIA1D1", "arachnotron", "\c[arachno]Arachnotron");
	
	addmonster(0.2, "FATTA1", "fatso", "\c[fatty]Mancubus");
	
	addmonster(0.225, "BOSSA1", "ropbaronofhell", "\c[pinky]Baron of Hell");
	addmonsteritem("baronofhellmanatoken");
	
	addmonster(0.3, "VILEA1D1", "archvile", "\c[vile]Arch-Vile");
	
	addmonster(5.0, "SPIDA1D1", "spidermastermind", "\c[mind]Spider Mastermind"); BossMonster();
	
	addmonster(6.0, "CYBRA1", "cyberdemon", "\c[g5]Cyberdemon"); BossMonster();
	
	addmonster(0.025, "SSWVA1", "wolfensteinss", "\chWolfenstein \cfSS");
	
	addmonster(0.01, "BAR1A0", "explosivebarrel", "\c[barrel]Explosive Barrel");
	/*
	AddMonster(0.02,  "POSSA1",   "Zombieman2", "Zombieman");
	AddMonster(0.035, "PRPSA1",   "PlasmaZombie", "Plasma Zombie");
	
	AddMonster(0.04,  "SPOSA1",   "Shotgunguy2", "Shotgun Zombie");
	AddMonster(0.07,  "FPOSA1",   "Supershotgunguy", "Super Shotgun Zombie");
	
	AddMonster(0.05,  "CPOSA1",   "Chaingunguy2", "Zombie Commando");
	AddMonster(0.075, "DPOSA1C1",   "DoubleChainGunGuy", "Double Chaingunner");
	
	AddMonster(0.02,  "TROOA1",   "Imp2", "Imp");
	AddMonster(0.045, "SLHVA1",   "SoulHarvester", "Soul Harvester");
	AddMonster(0.05,  "DRKVA1",   "DarkImp", "Dark Imp");
	
	AddMonster(0.045, "SARGA1",   "Pinky", "Demon");
	AddMonster(0.065, "MDMNA1C1", "MechDemon", "Mech Demon");
	AddMonster(0.0475,"SPTRA1",   "Spectre2", "Spectre");
    AddMonster(0.07,  "MSPCA1C1", "Mechtre", "Mechtre");
	
	AddMonster(0.07,  "SKULA1",   "LostSoul2", "Lost Soul"); FlyingMonster();
	
	AddMonster(0.15,  "HEADA1",   "Cacodemon2", "Cacodemon"); FlyingMonster();
	AddMonster(0.2,   "LANTA1",   "Cacolantern", "Cacolantern"); FlyingMonster();
	AddMonster(0.25,  "ABDNA1",   "Abaddon", "Abaddon"); FlyingMonster();
	
	AddMonster(0.2,   "PAINA1",   "PainElemental2", "Pain Elemental"); FlyingMonster();
	
	AddMonster(0.15,  "BOS2A1C1", "HellKnight2", "Hell Knight");
	
	AddMonster(0.25,  "BOSSA1",   "BaronofHell2", "Baron of Hell");
	AddMonster(0.325, "BELPA1",   "Belphegor", "Belphegor");
	
	AddMonster(0.15,  "SKELA1D1", "Revenant2", "Revenant");
	
	AddMonster(0.2,   "FATTA1",   "Mancubus", "Mancubus");
	AddMonster(0.275, "HECTA1",   "Hectebus", "Hectebus");
	
	AddMonster(0.2,   "BSPIA1D1", "Arachnotron2", "Arachnotron");
	AddMonster(0.25,   "CSPIA1D1", "ArachnoSentinel", "Arachno-Sentinel");
	
	AddMonster(0.4,   "VILEA1D1", "Archvile2", "Arch-Vile");
	
	AddMonster(5.0,   "SPIDA1D1", "Spidermastermind2", "Spider Mastermind"); BossMonster();
	
	AddMonster(6.0,   "CYBRA1",   "Cyberdemon2", "Cyberdemon"); BossMonster();
	
	AddMonster(0.02,  "SSWVA1",   "WolfensteinSS2", "Wolfenstein SS");
	
	AddMonster(0.01,  "BAR1A0",   "NewExplosiveBarrel", "Explosive Barrel");
	*/
}


